### ISSUE TITLE
React-icons usage on the www site requires a rewrite to be compatible

### ISSUE THREAD

**Issue by marcysutton** [jlengstorf/gatsby-feedback-widget#10]
While working on integrating the latest styles from this repo into Gatsbyjs.org, I'm finding that the version of `react-icons` on `www` is lower than this standalone repo, and therefore requiring a major update...after seeing @kylemathews PR for putting .org on a diet I'm concerned with the way react-icons tells you to import. Can we simplify to stick with v2 of react-icons to minimize impact of this widget? Would love some advice here.

Related: https://github.com/react-icons/react-icons/issues/154

**Comment by jlengstorf** [comment]
closed by #11
