### ISSUE TITLE
Styled Components conflict

### ISSUE THREAD

**Issue by donaldboulton** [jlengstorf/gatsby-feedback-widget#6]
I use styled components in my Gatsby site site noticed the work on the feedback widget so I thought I would try it = nice

Using styled-components and emotion/styled, will not work together nicely
emotion [error](https://github.com/emotion-js/emotion/issues/661)

A little more study I saw this Injection [Order](https://github.com/niekert/emotion-styled-injection-order-issue/blob/master/src/OverridenComponent.js)

So I replaced
`import styled from "@emotion/styled"`

With the below in buttons.js
`import styled, { css } from 'styled-components'`

And then

`import styled from 'styled-components'`

for the other files calling emotion styled.

And it works perfect using styled components with no conflict.

**Comment by jlengstorf** [comment]
Nice! We're planning to implement this into gatsbyjs.org, which uses Emotion, but this is really helpful for any future Googlers. 😄

**Comment by donaldboulton** [comment]
A real website has blogs, pages, adds, reviews comments ect...
And there are many things that Gatsby has decided we do not need, like the real ability to have our content found by search engines - spiders.

If you all are building for Googlers then you might think about, "in code structured micro-data", = no sudo json LD.
Pages, comments, posts, adds, reviews, products ect... need to have a correct structure for search engines.. Unless the  Googlers could find our site's and page's what good is Googling for non-indexed content. Gatsby need's to have some kind of usable structured microdata for Google search and other spiders, adding it to any real website site, so the Google spiders and other spiders can index there content

Now this is not true for Gatsbyjs as you all have 0 microdata in any of your sites and that's ok because of all the people searching for Gatsby stuff. So you are positioned by search hits, but the regular user with a web site, need's to have all the help he can get to have his content found so the Googlers will even know his site and pages are there.
I will add this to Gatsby's repo comments to see what the community thinks.
Thanks
Donald Boulton
