### ISSUE TITLE
Which endpoint

### ISSUE THREAD

**Issue by donaldboulton** [jlengstorf/gatsby-feedback-widget#9]
I would like to use the feedback widget what endpoint?
Got the .env part down what endpoint is used in your Netlify demo? or some idea.

Thanks
Donald Boulton

**Comment by jlengstorf** [comment]
Hey there! This widget assumes you have your own endpoint. We send it to our API as a [`submitFeedback` mutation](https://github.com/gatsbyjs/api.gatsbyjs.org/blob/master/src/graphql/public-schema.graphql#L9), so you could copy that if you like, or you could change it up to submit the data somewhere else.

Hope that helps!
